# SPDX-FileCopyrightText: 2026 Mark G. Russell
# SPDX-License-Identifier: MIT

"""Default OpenRoadCode ZeroMQ broker endpoints."""

BROKER_PUBLISHER_BIND_ENDPOINT = "tcp://0.0.0.0:5556"
BROKER_SUBSCRIBER_BIND_ENDPOINT = "tcp://0.0.0.0:5557"

LOCAL_PUBLISHER_ENDPOINT = "tcp://127.0.0.1:5556"
LOCAL_SUBSCRIBER_ENDPOINT = "tcp://127.0.0.1:5557"

__all__ = [
    "BROKER_PUBLISHER_BIND_ENDPOINT",
    "BROKER_SUBSCRIBER_BIND_ENDPOINT",
    "LOCAL_PUBLISHER_ENDPOINT",
    "LOCAL_SUBSCRIBER_ENDPOINT",
]
