
from apps.common.uiTheme.uiTheme import FONT_FAMILY

LIGHTING_PANEL_THEME = {
    "colors": {
        "background": "#07111f",
        "card_background": "#0d1b2e",
        "card_border": "#17456d",
        "text": "#e8f2ff",
        "muted_text": "#8fa8c4",
        "accent": "#1e88e5",
        "accent_dark": "#12385a",
        "disabled_control": "#2a3542",
        "error": "#ff6b6b",
        "ok": "#4ade80",
        "light_button_text": "#0b1220",
    },
    "layout": {
        "title": "Lighting",
        "connecting_text": "Connecting...",
        "connected_text": "Connected",
        "working_text": "Working...",
        "success_prefix": "● ",
        "power_title": "Power",
        "brightness_title": "Brightness",
        "colors_title": "Colors",
        "modes_title": "Modes",
        "power_on_text": "ON",
        "power_off_text": "OFF",
        "power_on_status": "Power on",
        "power_off_status": "Power off",
        "effect_label": "Effect",
        "music_label": "Music",
        "rainbow_text": "Rainbow",
        "strobe_text": "Strobe",
        "rainbow_pattern": "7 Color Flow",
        "strobe_pattern": "Strobe 7 Color",
        "initial_brightness": 75,
        "brightness_min": 0,
        "brightness_max": 100,
        "brightness_debounce_ms": 250,
        "callback_delay_ms": 0,
        "connection_refresh_ms": 500,
        "connection_retry_ms": 5000,
        "main_column": 0,
        "header_row": 0,
        "power_row": 1,
        "body_row": 2,
        "colors_row": 1,
        "row_zero": 0,
        "control_row": 0,
        "left_column": 0,
        "right_column": 1,
        "header_title_column": 0,
        "header_status_column": 1,
        "brightness_scale_row": 1,
        "brightness_columnspan": 2,
        "color_start_row": 1,
        "effect_label_row": 1,
        "effect_combo_row": 2,
        "music_label_row": 3,
        "music_combo_row": 4,
        "quick_row": 5,
        "fill_weight": 1,
        "power_columns": 2,
        "quick_columns": 2,
        "color_columns": 3,
        "section_columnspan": 3,
        "card_border_width": 1,
        "zero": 0,
        "horizontal_sticky": "ew",
        "fill_sticky": "nsew",
        "left_sticky": "w",
        "right_sticky": "e",
        "horizontal_orientation": "horizontal",
        "readonly_state": "readonly",
        "combobox_event": "<<ComboboxSelected>>",
        "flat_relief": "flat",
        "cursor": "hand2",
    },
    "profiles": {
        "default": {
            "outer_padx": 18,
            "header_pady": (10, 4),
            "section_gap": 6,
            "body_pady": (2, 10),
            "split_gap": 8,
            "section_bottom_gap": 10,
            "button_pady": 8,
            "power_button_ipady": 9,
            "title_font": (FONT_FAMILY, 24, "bold"),
            "status_font": (FONT_FAMILY, 12, "bold"),
            "brightness_font": (FONT_FAMILY, 16, "bold"),
            "brightness_length": 320,
            "brightness_scale_pady": (8, 4),
            "color_button_font": (FONT_FAMILY, 12, "bold"),
            "color_button_padx": 6,
            "color_button_pady": 7,
            "color_button_ipady": 13,
            "mode_label_font": (FONT_FAMILY, 12, "bold"),
            "combobox_font": (FONT_FAMILY, 13),
            "combobox_ipady": 5,
            "effect_label_pady": (6, 4),
            "music_label_pady": (20, 4),
            "quick_pady": (22, 0),
            "quick_gap": 6,
            "quick_button_ipady": 8,
            "section_padx": 14,
            "section_pady": 10,
            "section_title_font": (FONT_FAMILY, 15, "bold"),
            "button_font": (FONT_FAMILY, 13, "bold"),
        },
    },
    "color_presets": (
        {"name": "Red", "hex": "#ff2b2b", "rgb": (255, 0, 0)},
        {"name": "Green", "hex": "#00d26a", "rgb": (0, 255, 0)},
        {"name": "Blue", "hex": "#2684ff", "rgb": (0, 0, 255)},
        {
            "name": "White",
            "hex": "#f8fafc",
            "rgb": (255, 255, 255),
            "use_dark_text": True,
        },
        {"name": "Amber", "hex": "#ffb020", "rgb": (255, 120, 0)},
        {"name": "Purple", "hex": "#b455ff", "rgb": (160, 0, 255)},
    ),
    "patterns": (
        ("Off", 0),
        ("Dreaming", 1),
        ("7 Color Flow", 3),
        ("Trail 7 Color", 23),
        ("Stream 7 Color", 39),
        ("Curtain 7 Color", 57),
        ("Hop 7 Color", 75),
        ("Strobe 7 Color", 78),
        ("Gradual 7 Color", 81),
    ),
    "music_modes": (
        ("Off", 0),
        ("Music EQ 1", 1),
        ("Music EQ 2", 2),
        ("Music EQ 3", 3),
        ("Music EQ 4", 4),
    ),
}
