# SPDX-FileCopyrightText: 2026 Mark G. Russell
# SPDX-License-Identifier: MIT

from apps.common.uiTheme.uiTheme import COLORS, FONTS, FONT_FAMILY

RADIO_PANEL_THEME = {
    "colors": {
        "panel_bg": COLORS["app_bg"],
        "tile_bg": COLORS["tile_bg"],
        "tile_border": COLORS["tile_border"],
        "tile_title": COLORS["tile_title"],
        "tile_subtitle": COLORS["tile_subtitle"],
        "tile_detail": COLORS["tile_detail"],
        "primary_value": COLORS["status_primary_value"],
        "telemetry_value": COLORS["status_telemetry_value"],
        "status_bg": COLORS["status_bg"],
        "status_label": COLORS["status_label"],
        "control_accent": COLORS["radio_control_accent"],
        "bank_button_bg": COLORS["radio_bank_button_bg"],
        "bank_button_fg": COLORS["radio_bank_button_fg"],
        "bank_button_active_bg": COLORS["radio_bank_button_active_bg"],
        "bank_button_active_fg": COLORS["radio_bank_button_active_fg"],
        "active_preset_bg": COLORS["radio_active_preset_bg"],
        "active_preset_fg": COLORS["radio_active_preset_fg"],
        "active_preset_border": COLORS["radio_active_preset_border"],
    },
    "layout": {
        "root_column": 0,
        "content_row": 0,
        "status_row": 1,
        "control_column": 0,
        "preset_column": 1,
        "control_left_column": 0,
        "control_right_column": 1,
        "control_column_count": 2,
        "control_row_count": 3,
        "bank_column_count": 3,
        "tile_column": 0,
        "preset_number_row": 0,
        "preset_value_row": 1,
        "preset_detail_row": 2,
        "bank_nav_row": 1,
        "nav_row": 0,
        "bank_previous_column": 0,
        "bank_label_column": 1,
        "bank_next_column": 2,
        "icon_column": 0,
        "text_column": 1,
        "body_row": 0,
        "status_content_row": 0,
        "fill_weight": 1,
        "fixed_weight": 0,
        "zero": 0,
        "zero_padding": (0, 0),
        "border_width": 0,
        "expand": True,
        "fill_sticky": "nsew",
        "horizontal_sticky": "ew",
        "northwest_sticky": "nw",
        "north_sticky": "n",
        "horizontal_fill": "x",
        "both_fill": "both",
        "top_side": "top",
        "left_side": "left",
        "left_anchor": "w",
        "center_anchor": "center",
        "left_justify": "left",
        "interactive_cursor": "hand2",
        "fm_panel_key": "fm_radio",
        "fm_precision": 1,
        "default_precision": 3,
        "poll_interval_ms": 2000,
        "rds_mode_name": "WFM",
        "empty_value": "--",
    },
    "profiles": {
        "compact": {
            "main_column_weights": (3, 2),
            "column_gap": 6,
            "control_tile_pad": 4,
            "preset_tile_pad": 4,
            "tile_border_width": 2,
            "control_accent_height": 4,
            "control_body_padx": 5,
            "control_body_pady": 6,
            "control_icon_font": (FONT_FAMILY, 20, "bold"),
            "control_icon_width": 1,
            "control_icon_gap": 4,
            "control_icon_pady": 1,
            "control_title_font": (FONT_FAMILY, 16, "bold"),
            "control_subtitle_font": (FONT_FAMILY, 10),
            "control_detail_font": (FONT_FAMILY, 8),
            "control_text_wrap": 145,
            "control_subtitle_pady": 4,
            "control_detail_pady": 2,
            "preset_number_font": (FONT_FAMILY, 10, "bold"),
            "preset_frequency_font": (FONT_FAMILY, 17, "bold"),
            "preset_detail_font": (FONT_FAMILY, 8),
            "preset_number_padx": 8,
            "preset_number_pady": 5,
            "preset_value_padx": 6,
            "preset_detail_padx": 6,
            "preset_detail_pady": 5,
            "bank_button_font": (FONT_FAMILY, 8),
            "bank_nav_top_pad": 4,
            "bank_button_padx": 8,
            "bank_button_pady": 3,
            "bank_button_gap": 4,
            "bank_label_padx": 4,
            "status_top_pad": 6,
            "status_ipady": 3,
            "status_group_padx": 4,
            "status_value_gap": 4,
            "status_font": (FONT_FAMILY, 9),
        },
        "normal": {
            "main_column_weights": (3, 2),
            "column_gap": 6,
            "control_tile_pad": 6,
            "preset_tile_pad": 6,
            "tile_border_width": 2,
            "control_accent_height": 4,
            "control_body_padx": 14,
            "control_body_pady": 10,
            "control_icon_font": (FONT_FAMILY, 28, "bold"),
            "control_icon_width": 2,
            "control_icon_gap": 12,
            "control_icon_pady": 2,
            "control_title_font": (FONT_FAMILY, 24, "bold"),
            "control_subtitle_font": (FONT_FAMILY, 14),
            "control_detail_font": (FONT_FAMILY, 11),
            "control_text_wrap": 260,
            "control_subtitle_pady": 7,
            "control_detail_pady": 3,
            "preset_number_font": (FONT_FAMILY, 13, "bold"),
            "preset_frequency_font": (FONT_FAMILY, 24, "bold"),
            "preset_detail_font": (FONT_FAMILY, 13),
            "preset_number_padx": 10,
            "preset_number_pady": 7,
            "preset_value_padx": 8,
            "preset_detail_padx": 8,
            "preset_detail_pady": 9,
            "bank_button_font": FONTS["status"],
            "bank_nav_top_pad": 4,
            "bank_button_padx": 8,
            "bank_button_pady": 3,
            "bank_button_gap": 4,
            "bank_label_padx": 4,
            "status_top_pad": 6,
            "status_ipady": 3,
            "status_group_padx": 4,
            "status_value_gap": 4,
            "status_font": FONTS["status"],
        },
    },
}