from . import COLORS, FONTS, FONT_FAMILY

SPOTIFY_PANEL_THEME = {
    "colors": {
        "background": COLORS["app_bg"],
        "card_background": "#151a18",
        "card_border": "#30483a",
        "title": COLORS["tile_title"],
        "subtitle": COLORS["tile_subtitle"],
        "detail": COLORS["tile_detail"],
        "status": "#1ED760",
        "button_background": "#222a26",
        "button_foreground": COLORS["volume_button_fg"],
        "button_active_background": "#1ED760",
        "button_active_foreground": "#07140c",
        "progress_track": COLORS["tile_border"],
        "progress_fill": "#1ED760",
    },
    "layout": {
        "title": "SPOTIFY",
        "initial_status": "Spotify",
        "configuration_required_status": "Spotify setup required",
        "configuration_required_title": "Spotify is not configured",
        "configuration_required_detail": (
            "Run scripts/installers/install_spotify.sh"
        ),
        "empty_value": "--",
        "empty_device_text": "Device: --",
        "empty_progress_text": "--:-- / --:--",
        "empty_volume_text": "Volume: --%",
        "device_template": "Device: {device}",
        "volume_template": "Volume: {volume}%",
        "progress_template": "{progress} / {duration}",
        "previous_text": "◀◀",
        "play_pause_text": "▶",
        "next_text": "▶▶",
        "play_text": "▶",
        "pause_text": "Ⅱ",
        "volume_down_text": "−",
        "volume_up_text": "+",
        "volume_not_supported_text": "Volume control not supported",
        "left_side": "left",
        "right_side": "right",
        "left_anchor": "w",
        "right_anchor": "e",
        "center_anchor": "center",
        "fill_horizontal": "x",
        "fill_both": "both",
        "flat_relief": "flat",
        "cursor": "hand2",
        "zero": 0,
        "click_event": "<Button-1>",
        "drag_event": "<B1-Motion>",
        "configure_event": "<Configure>",
        "canvas_all_tag": "all",
        "empty_outline": "",
        "refresh_interval_ms": 1000,
        "volume_step": 5,
        "default_volume": 50,
        "minimum_volume": 0,
        "maximum_volume": 100,
        "minimum_canvas_width": 1,
        "fallback_canvas_width": 500,
        "progress_min_ratio": 0.0,
        "progress_max_ratio": 1.0,
        "minimum_progress_percent": 0.0,
        "maximum_progress_percent": 100.0,
        "progress_left": 0,
        "card_border_width": 2,
    },
    "profiles": {
        "default": {
            "outer_pad": 10,
            "header_pady": (8, 2),
            "header_title_font": FONTS["tile_title"],
            "status_font": FONTS["status"],
            "track_font": (FONT_FAMILY, 28, "bold"),
            "artist_font": (FONT_FAMILY, 17),
            "detail_font": FONTS["tile_detail"],
            "lyrics_font": (FONT_FAMILY, 11),
            "lyrics_current_font": (FONT_FAMILY, 13, "bold"),
            "button_font": FONTS["volume_button"],
            "text_wrap": 360,
            "lyrics_width": 360,
            "lyrics_wrap": 340,
            "text_padx": 14,
            "track_pady": (10, 4),
            "album_pady": (2, 6),
            "progress_canvas_height": 14,
            "progress_padx": 28,
            "progress_canvas_pady": (6, 1),
            "progress_text_pady": (0, 5),
            "progress_track_top": 4,
            "progress_track_bottom": 10,
            "controls_pady": (4, 4),
            "transport_button_width": 5,
            "transport_button_gap": 8,
            "bottom_padx": 18,
            "bottom_pady": (2, 6),
            "volume_button_width": 3,
            "volume_button_gap": 3,
            "volume_text_width": 13,
            "cover_size": 190,
            "hero_padx": 16,
            "hero_pady": (18, 6),
            "cover_gap": 16,
        },
    },
}
