from . import COLORS, FONTS, FONT_FAMILY

SPOTIFY_PANEL_THEME = {
    "colors": {
        "background": COLORS["app_bg"],
        "card_background": COLORS["tile_bg"],
        "card_border": COLORS["tile_border"],
        "title": COLORS["tile_title"],
        "subtitle": COLORS["tile_subtitle"],
        "detail": COLORS["tile_detail"],
        "status": COLORS["status_telemetry_value"],
        "button_background": COLORS["volume_button_bg"],
        "button_foreground": COLORS["volume_button_fg"],
        "button_active_background": COLORS["top_bar_active"],
        "button_active_foreground": COLORS["top_bar_fg"],
        "progress_track": COLORS["tile_border"],
        "progress_fill": COLORS["tile_accent"],
    },
    "layout": {
        "title": "SPOTIFY",
        "initial_status": "Spotify",
        "configuration_required_status": "Spotify setup required",
        "configuration_required_title": "Spotify is not configured",
        "configuration_required_detail": (
            "Run scripts/installers/install_spotify.sh"
        ),
        "empty_value": "--",
        "empty_device_text": "Device: --",
        "empty_progress_text": "--:-- / --:--",
        "empty_volume_text": "Volume: --%",
        "device_template": "Device: {device}",
        "volume_template": "Volume: {volume}%",
        "progress_template": "{progress} / {duration}",
        "previous_text": "⏮",
        "play_pause_text": "⏯",
        "next_text": "⏭",
        "play_text": "▶",
        "pause_text": "⏸",
        "volume_down_text": "−",
        "volume_up_text": "+",
        "volume_not_supported_text": "Volume control not supported",
        "left_side": "left",
        "right_side": "right",
        "left_anchor": "w",
        "right_anchor": "e",
        "center_anchor": "center",
        "fill_horizontal": "x",
        "fill_both": "both",
        "flat_relief": "flat",
        "cursor": "hand2",
        "zero": 0,
        "click_event": "<Button-1>",
        "drag_event": "<B1-Motion>",
        "configure_event": "<Configure>",
        "canvas_all_tag": "all",
        "empty_outline": "",
        "refresh_interval_ms": 1000,
        "volume_step": 5,
        "default_volume": 50,
        "minimum_volume": 0,
        "maximum_volume": 100,
        "minimum_canvas_width": 1,
        "fallback_canvas_width": 500,
        "progress_min_ratio": 0.0,
        "progress_max_ratio": 1.0,
        "minimum_progress_percent": 0.0,
        "maximum_progress_percent": 100.0,
        "progress_left": 0,
        "card_border_width": 2,
    },
    "profiles": {
        "default": {
            "outer_pad": 14,
            "header_pady": (14, 4),
            "header_title_font": FONTS["tile_title"],
            "status_font": FONTS["status"],
            "track_font": (FONT_FAMILY, 34, "bold"),
            "artist_font": (FONT_FAMILY, 20),
            "detail_font": FONTS["tile_detail"],
            "button_font": FONTS["volume_button"],
            "text_wrap": 700,
            "text_padx": 14,
            "track_pady": (18, 4),
            "album_pady": (2, 10),
            "progress_canvas_height": 18,
            "progress_padx": 28,
            "progress_canvas_pady": (8, 2),
            "progress_text_pady": (0, 10),
            "progress_track_top": 6,
            "progress_track_bottom": 12,
            "controls_pady": (4, 12),
            "transport_button_width": 5,
            "transport_button_gap": 8,
            "bottom_padx": 18,
            "bottom_pady": (4, 12),
            "volume_button_width": 3,
            "volume_button_gap": 3,
            "volume_text_width": 13,
        },
    },
}
