(()=>{
  const root=window.OpenRoadCodeWeb=window.OpenRoadCodeWeb||{};
  const button=document.getElementById('music-mic-toggle'),status=document.getElementById('music-mic-status'),spectrum=document.getElementById('music-spectrum'),labels=document.getElementById('music-spectrum-labels'),debug=document.getElementById('music-debug');
  const beatCard=document.getElementById('music-beat'),beatStrength=document.getElementById('music-beat-strength'),lightbar=document.getElementById('music-lightbar'),driveLights=document.getElementById('music-drive-lights'),lightStatus=document.getElementById('music-light-status');if(!button||!spectrum||!root.MicrophoneMusicAnalyzer)return;
  const analyzer=new root.MicrophoneMusicAnalyzer();window.__openRoadMusicAnalyzer=analyzer;
  const bars=Array.from({length:24},()=>{const x=document.createElement('div');x.style.cssText='flex:1;min-width:0;height:2%;background:linear-gradient(to top,#20c85a 0%,#34d058 34%,#dbe63b 48%,#ffd21c 62%,#ff8a18 78%,#ef3b24 100%);border-radius:4px 4px 0 0;transition:height .025s linear';spectrum.appendChild(x);return x;});['31','41','54','70','92','120','157','205','268','350','457','597','780','1k','1.3k','1.7k','2.2k','2.9k','3.8k','5k','6.5k','8.5k','11k','16k'].forEach((label,i)=>{const x=document.createElement('div');x.textContent=(i%2===0||i===23)?label:'';labels.appendChild(x)});root.SpectrumDisplay?.install();
  function upgradeKit(){const kit=document.querySelector('#music-drum-kit .mv-kit');if(!kit)return false;if(document.getElementById('drum-tom-mid'))return true;kit.innerHTML=`<div id="drum-cymbal-left" class="mv-cymbal mv-cymbal-left"></div><span class="mv-kit-name mv-name-hihat">HI-HAT</span><div id="drum-cymbal-right" class="mv-cymbal mv-cymbal-right"></div><span class="mv-kit-name mv-name-crash">CRASH</span><div id="drum-tom-high" class="mv-drum mv-tom mv-tom-high"><span class="mv-drum-label">HIGH TOM</span></div><div id="drum-tom-mid" class="mv-drum mv-tom mv-tom-mid"><span class="mv-drum-label">MID TOM</span></div><div id="drum-tom-low" class="mv-drum mv-tom mv-tom-low"><span class="mv-drum-label">LOW TOM</span></div><div id="drum-snare" class="mv-drum mv-snare"><span class="mv-drum-label">SNARE</span></div><div id="drum-kick-left" class="mv-drum mv-kick mv-kick-left"><span class="mv-drum-label">LEFT KICK</span></div><div id="drum-kick-right" class="mv-drum mv-kick mv-kick-right"><span class="mv-drum-label">RIGHT KICK</span></div>`;return true}
  function upgradeMeters(){const grid=document.querySelector('#mv-activity .mv-meter-grid');if(!grid||document.getElementById('mv-seg-tomMid'))return!!grid;const high=document.getElementById('mv-seg-tomHigh')?.closest('.mv-meter');if(!high)return false;const meter=document.createElement('div');meter.className='mv-meter mv-tom-mid-color';meter.innerHTML=`<div class="mv-meter-name">MID TOM</div><div id="mv-seg-tomMid" class="mv-segments">${'<i class="mv-segment"></i>'.repeat(12)}</div>`;high.after(meter);grid.classList.add('mv-meter-grid-six');return true}
  let uiAttempts=0;const upgradeUi=()=>{const link=document.querySelector('link[data-mv]');if(link&&!link.href.includes('v=6'))link.href='/web-assets/audio-analysis/music_visualizer.css?v=6';const kitReady=upgradeKit(),metersReady=upgradeMeters();if(kitReady)root.KickMode?.install();if(kitReady&&metersReady)return;if(uiAttempts++<40)setTimeout(upgradeUi,50)};setTimeout(upgradeUi,10);
  let beatFlashUntil=0,lastLightSend=0,lastColor='',lastBrightness=-1,smoothBass=0,smoothMid=0,smoothTreble=0,smoothEnergy=0,lastHitId=0,lastSecondaryHitId=0;
  const smooth=(o,n,a=.34,r=.11)=>o+(n-o)*(n>o?a:r),rgbHex=(r,g,b)=>'#'+[r,g,b].map(v=>Math.round(Math.max(0,Math.min(255,v))).toString(16).padStart(2,'0')).join('').toUpperCase(),lightColor=(b,m,t)=>{const total=b+m+t+.001;return rgbHex(255*(b+m*.45)/total,255*(m+t*.35)/total,255*(t+m*.18)/total)};
  const post=async payload=>{const r=await fetch('/api/lighting/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw Error(`lighting HTTP ${r.status}`)},drivePhysical=async(color,brightness)=>{if(!driveLights.checked||performance.now()-lastLightSend<120)return;lastLightSend=performance.now();try{if(color!==lastColor){await post({command:'color',value:color});lastColor=color}if(Math.abs(brightness-lastBrightness)>=5){await post({command:'brightness',value:brightness});lastBrightness=brightness}lightStatus.textContent='Driving lighting backend · responsive smoothed output'}catch(e){lightStatus.textContent=`Lighting error: ${e.message}`}};driveLights.onchange=async()=>{if(driveLights.checked){try{await post({command:'power',value:true});lightStatus.textContent='Lighting output enabled.'}catch(e){lightStatus.textContent=`Lighting error: ${e.message}`}}else lightStatus.textContent='Preview only.'};
  const pulseState={snare:{until:0,duration:145,strength:0},tomHigh:{until:0,duration:145,strength:0},tomMid:{until:0,duration:145,strength:0},tomLow:{until:0,duration:150,strength:0},cymbal:{prev:0,until:0,duration:210,strength:1}};
  const fireHit=(hit,secondary=false)=>{if(!hit)return;if(secondary){if(hit.id===lastSecondaryHitId)return;lastSecondaryHitId=hit.id}else{if(hit.id===lastHitId)return;lastHitId=hit.id}const p=pulseState[hit.type];if(p){p.until=performance.now()+p.duration;p.strength=Math.max(secondary?.72:1,Math.min(1,hit.strength||0))}};
  const triggerCymbal=value=>{const p=pulseState.cymbal,rise=Math.max(0,value-p.prev);p.prev=value;if(rise>.055&&value>.12){p.until=performance.now()+p.duration;p.strength=1}};
  const pulseValue=name=>{const p=pulseState[name],remaining=p.until-performance.now();if(remaining<=0)return 0;const t=remaining/p.duration;return(Math.sin(Math.PI*Math.min(1,Math.max(0,t)))**.42)*(p.strength||1)};
  const setPunch=(id,value,color,base='',amount)=>{const el=document.getElementById(id);if(!el)return;const growth=amount??(id.includes('snare')?.72:id.includes('tom-mid')?.68:id.includes('tom-')?.66:id.includes('kick')?.34:.31),scale=1+value*growth;el.style.transform=`${base} scale(${scale})`;el.style.filter=`brightness(${1+value*.42}) saturate(${1+value*.58})`;el.style.boxShadow=`inset 0 0 ${5+value*15}px ${color},0 0 ${9+value*68}px ${color},0 0 ${20+value*56}px ${color}`};
  const renderMidMeter=value=>{const seg=document.getElementById('mv-seg-tomMid');if(!seg)return;const on=Math.round(Math.max(0,Math.min(1,value))*12),color='#38d6b4';[...seg.children].forEach((x,i)=>{const active=i<on;x.style.background=active?color:'#18222e';x.style.boxShadow=active&&i>=on-2?`0 0 9px ${color}`:'none';x.style.opacity=active?1:.55})};
  const emphasizeDrums=a=>{if(!a)return;fireHit(a.hit);fireHit(a.secondaryHit,true);root.KickMode?.render(a.kick||0,setPunch);triggerCymbal(a.cymbal||0);setPunch('drum-snare',pulseValue('snare'),'rgba(255,198,46,.68)','translateX(-50%)');setPunch('drum-tom-high',pulseValue('tomHigh'),'rgba(168,76,255,.68)');setPunch('drum-tom-mid',pulseValue('tomMid'),'rgba(56,214,180,.68)');setPunch('drum-tom-low',pulseValue('tomLow'),'rgba(40,182,255,.68)');const cymbal=pulseValue('cymbal');for(const[id,dir]of[['drum-cymbal-left',-1],['drum-cymbal-right',1]]){const el=document.getElementById(id);if(!el)continue;el.style.transform=`scaleX(${1+cymbal*.17}) scaleY(${1+cymbal*.09}) rotate(${dir*cymbal*9}deg)`;el.style.filter=`brightness(${1+cymbal*.5}) saturate(${1+cymbal*.32})`;el.style.boxShadow=`0 0 ${12+cymbal*50}px rgba(255,210,45,${.18+cymbal*.64})`}};
  const render=state=>{if(state.activity&&root.PercussionClassifier)state.activity=root.PercussionClassifier.classify(analyzer,state.activity);if(root.SpectrumDisplay?.filterActivity&&state.activity)state.activity=root.SpectrumDisplay.filterActivity(state.activity,analyzer);document.getElementById('music-level').value=state.level;document.getElementById('music-bass').value=state.bass;document.getElementById('music-mid').value=state.mid;document.getElementById('music-treble').value=state.treble;document.getElementById('activity-kick').value=state.activity?.kick??0;document.getElementById('activity-bass').value=state.activity?.bass??0;document.getElementById('activity-snare').value=state.activity?.snare??0;document.getElementById('activity-cymbal').value=state.activity?.cymbal??0;if(root.SpectrumDisplay)root.SpectrumDisplay.render(state,analyzer,bars);else state.spectrum.forEach((v,i)=>bars[i].style.height=`${Math.max(2,v*100)}%`);renderMidMeter(state.activity?.tomMid||0);emphasizeDrums(state.activity);smoothBass=smooth(smoothBass,state.bass,.34,.11);smoothMid=smooth(smoothMid,state.mid,.30,.10);smoothTreble=smooth(smoothTreble,state.treble,.27,.09);smoothEnergy=smooth(smoothEnergy,Math.min(1,state.level*.30+state.bass*.42+state.mid*.18+state.treble*.10),.36,.10);const pulse=state.beat?Math.min(.18,.07+state.beatStrength*.11):0,visualEnergy=Math.min(1,smoothEnergy+pulse),color=lightColor(smoothBass,smoothMid,smoothTreble),brightness=Math.round(14+80*visualEnergy);lightbar.style.background=color;lightbar.style.filter=`brightness(${.70+visualEnergy*.82})`;lightbar.style.boxShadow=`0 0 ${8+visualEnergy*13}px ${color},0 0 ${20+visualEnergy*36}px ${color}`;drivePhysical(color,brightness);if(state.beat){beatFlashUntil=performance.now()+70;beatStrength.textContent=`HIT · ${state.beatStrength.toFixed(2)}`}if(performance.now()<beatFlashUntil){beatCard.style.background='#5b2020';beatCard.style.boxShadow='0 0 18px rgba(255,72,32,.45)'}else{beatCard.style.background='#151a20';beatCard.style.boxShadow='none';if(!state.beat)beatStrength.textContent='listening'}debug.textContent=`${state.sampleRateHz} Hz · FFT ${state.fftSize} · flux ${state.beatFlux.toFixed(4)}`};
  button.onclick=async()=>{const enabled=button.dataset.enabled==='1';try{if(enabled){await analyzer.stop();button.dataset.enabled='0';button.textContent='START MICROPHONE';status.textContent='Microphone stopped.';beatStrength.textContent='waiting…';root.SpectrumDisplay?.setCaptureActive(false)}else{await analyzer.start(render);button.dataset.enabled='1';button.textContent='STOP MICROPHONE';status.textContent='Microphone active. Play some music nearby.';root.SpectrumDisplay?.setCaptureActive(true)}}catch(error){status.textContent=`Microphone error: ${error.message}`}};
})();