(()=>{
  const root=window.OpenRoadCodeWeb=window.OpenRoadCodeWeb||{};
  const button=document.getElementById('music-mic-toggle'),status=document.getElementById('music-mic-status'),spectrum=document.getElementById('music-spectrum'),labels=document.getElementById('music-spectrum-labels'),debug=document.getElementById('music-debug');
  if(!button||!spectrum||!root.MicrophoneMusicAnalyzer)return;
  const analyzer=new root.MicrophoneMusicAnalyzer();window.__openRoadMusicAnalyzer=analyzer;
  const bars=Array.from({length:24},()=>{const x=document.createElement('div');x.style.cssText='flex:1;min-width:0;height:2%;background:linear-gradient(to top,#20c85a 0%,#34d058 34%,#dbe63b 48%,#ffd21c 62%,#ff8a18 78%,#ef3b24 100%);border-radius:4px 4px 0 0;transition:height .025s linear';spectrum.appendChild(x);return x});
  ['31','41','54','70','92','120','157','205','268','350','457','597','780','1k','1.3k','1.7k','2.2k','2.9k','3.8k','5k','6.5k','8.5k','11k','16k'].forEach((label,i)=>{const x=document.createElement('div');x.textContent=(i%2===0||i===23)?label:'';labels.appendChild(x)});
  root.SpectrumDisplay?.install();

  function upgradeKit(){const kit=document.querySelector('#music-drum-kit .mv-kit');if(!kit)return false;if(document.getElementById('drum-tom-mid'))return true;kit.innerHTML=`<div id="drum-cymbal-left" class="mv-cymbal mv-cymbal-left"></div><span class="mv-kit-name mv-name-hihat">HI-HAT</span><div id="drum-cymbal-right" class="mv-cymbal mv-cymbal-right"></div><span class="mv-kit-name mv-name-crash">CRASH</span><span class="mv-drum-label mv-label-tom-high">HIGH TOM</span><div id="drum-tom-high" class="mv-drum mv-tom mv-tom-high"></div><span class="mv-drum-label mv-label-tom-mid">MID TOM</span><div id="drum-tom-mid" class="mv-drum mv-tom mv-tom-mid"></div><span class="mv-drum-label mv-label-tom-low">LOW TOM</span><div id="drum-tom-low" class="mv-drum mv-tom mv-tom-low"></div><span class="mv-drum-label mv-label-snare">SNARE</span><div id="drum-snare" class="mv-drum mv-snare"></div><div id="drum-kick-left" class="mv-drum mv-kick mv-kick-left"><span class="mv-drum-label">LEFT KICK</span></div><div id="drum-kick-right" class="mv-drum mv-kick mv-kick-right"><span class="mv-drum-label">RIGHT KICK</span></div>`;return true}
  function upgradeMeters(){const grid=document.querySelector('#mv-activity .mv-meter-grid');if(!grid||document.getElementById('mv-seg-tomMid'))return!!grid;const high=document.getElementById('mv-seg-tomHigh')?.closest('.mv-meter');if(!high)return false;const meter=document.createElement('div');meter.className='mv-meter mv-tom-mid-color';meter.innerHTML=`<div class="mv-meter-name">MID TOM</div><div id="mv-seg-tomMid" class="mv-segments">${'<i class="mv-segment"></i>'.repeat(12)}</div>`;high.after(meter);grid.classList.add('mv-meter-grid-six');return true}
  let uiAttempts=0;const upgradeUi=()=>{const kitReady=upgradeKit(),metersReady=upgradeMeters();if(kitReady)root.KickMode?.install();root.WebGLMusicVisualizer?.install();if(kitReady&&metersReady)return;if(uiAttempts++<40)setTimeout(upgradeUi,50)};setTimeout(upgradeUi,10);

  const pulse={snare:0,tomHigh:0,tomMid:0,tomLow:0,cymbal:0};
  const setPunch=(id,value,color,base='',amount)=>{const el=document.getElementById(id);if(!el)return;const growth=amount??(id.includes('snare')?.35:id.includes('tom-mid')?.40:id.includes('tom-')?.38:id.includes('kick')?.34:.31);el.style.transform=`${base} scale(${1+value*growth})`;el.style.filter=`brightness(${1+value*.32}) saturate(${1+value*.42})`;el.style.boxShadow=`inset 0 0 ${5+value*12}px ${color},0 0 ${8+value*38}px ${color}`};
  function renderMidMeter(value){const seg=document.getElementById('mv-seg-tomMid');if(!seg)return;const on=Math.round(Math.max(0,Math.min(1,value))*12),color='#38d6b4';[...seg.children].forEach((x,i)=>{x.style.background=i<on?color:'#18222e';x.style.opacity=i<on?1:.55})}
  function renderDrums(p){for(const key of Object.keys(pulse))pulse[key]=Math.max(p[key]||0,pulse[key]*.72);root.KickMode?.render(p.kick||0,setPunch);setPunch('drum-snare',pulse.snare,'rgba(255,198,46,.68)','translateX(-50%)');setPunch('drum-tom-high',pulse.tomHigh,'rgba(168,76,255,.68)');setPunch('drum-tom-mid',pulse.tomMid,'rgba(56,214,180,.68)');setPunch('drum-tom-low',pulse.tomLow,'rgba(40,182,255,.68)');const c=pulse.cymbal;for(const[id,dir]of[['drum-cymbal-left',-1],['drum-cymbal-right',1]]){const el=document.getElementById(id);if(el){el.style.transform=`scaleX(${1+c*.17}) scaleY(${1+c*.09}) rotate(${dir*c*9}deg)`;el.style.filter=`brightness(${1+c*.5}) saturate(${1+c*.32})`}}renderMidMeter(p.tomMid||0)}
  function normalize(payload){const a=payload?.audio||payload||{},p=payload?.percussion||{};return{level:a.level||0,peak:a.peak||0,bass:a.bass||0,mid:a.mid||0,treble:a.treble||0,spectrum:a.spectrum||[],percussion:{kick:p.kick||0,snare:p.snare||0,tomLow:p.tom_low??p.tomLow??0,tomMid:p.tom_mid??p.tomMid??0,tomHigh:p.tom_high??p.tomHigh??0,cymbal:p.cymbal||0},calibrated:!!payload?.calibrated,sensitivity:payload?.sensitivity??1}}
  function render(payload){const s=normalize(payload);root.WebGLMusicVisualizer?.render(s);document.getElementById('music-level').value=s.level;document.getElementById('music-bass').value=s.bass;document.getElementById('music-mid').value=s.mid;document.getElementById('music-treble').value=s.treble;document.getElementById('activity-kick').value=s.percussion.kick;document.getElementById('activity-bass').value=s.bass;document.getElementById('activity-snare').value=s.percussion.snare;document.getElementById('activity-cymbal').value=s.percussion.cymbal;root.SpectrumDisplay?.render(payload,bars);renderDrums(s.percussion);if(debug)debug.textContent=`Shared Python MusicAnalyzer · sensitivity ${Math.round(s.sensitivity*100)}%${s.calibrated?' · zeroized':''}`}
  root.MusicVisualizerPage={render};
  button.onclick=async()=>{const enabled=button.dataset.enabled==='1';try{if(enabled){await analyzer.stop();button.dataset.enabled='0';button.textContent='START MICROPHONE';status.textContent='Microphone stopped.';root.SpectrumDisplay?.setCaptureActive(false)}else{root.SpectrumDisplay?.setSource('browser');await analyzer.start(render);button.dataset.enabled='1';button.textContent='STOP MICROPHONE';status.textContent='Microphone active · PCM sent to shared Python analyzer.';root.SpectrumDisplay?.setCaptureActive(true)}}catch(error){status.textContent=`Microphone error: ${error.message}`}};
})();