(()=>{
  const root=window.OpenRoadCodeWeb=window.OpenRoadCodeWeb||{};
  const button=document.getElementById('music-visualizer-toggle'),linuxButton=document.getElementById('music-visualizer-linux-toggle'),status=document.getElementById('music-visualizer-status'),lightingButton=document.getElementById('music-lighting-toggle'),lightingStatus=document.getElementById('music-lighting-status'),songButton=document.getElementById('music-song-identify'),songStatus=document.getElementById('music-song-status'),songTitle=document.getElementById('music-song-title'),songArtist=document.getElementById('music-song-artist'),songAlbum=document.getElementById('music-song-album'),sensitivity=document.getElementById('music-visualizer-sensitivity'),sensitivityValue=document.getElementById('music-visualizer-sensitivity-value');
  const meters={bass:document.getElementById('music-bass'),mid:document.getElementById('music-mid'),treble:document.getElementById('music-treble')};if(!button||!root.BrowserPcmCapture)return;
  const capture=new root.BrowserPcmCapture();let state={level:0,bass:0,mid:0,treble:0,spectrum:Array(24).fill(0),percussion:{}};let linuxRunning=false,linuxPoll=null;
  const clamp01=value=>Math.max(0,Math.min(1,Number(value)||0));
  const response=(value,gain)=>1-Math.exp(-clamp01(value)*gain);
  function visualGain(){return Math.max(1,Number(sensitivity?.value)||10)}
  function visualState(raw){
    const gain=visualGain(),percussionGain=gain*4,percussion=raw?.percussion||{};
    return {
      ...raw,
      level:response(raw?.level,gain),bass:response(raw?.bass,gain),mid:response(raw?.mid,gain),treble:response(raw?.treble,gain),
      spectrum:(raw?.spectrum||[]).map(value=>response(value,gain)),
      percussion:{
        ...percussion,
        kick:response(percussion.kick,percussionGain),bass:response(percussion.bass,percussionGain),snare:response(percussion.snare,percussionGain),
        tom_low:response(percussion.tom_low??percussion.tomLow,percussionGain),tom_mid:response(percussion.tom_mid??percussion.tomMid,percussionGain),tom_high:response(percussion.tom_high??percussion.tomHigh,percussionGain),
        cymbal:response(percussion.cymbal,percussionGain)
      }
    };
  }
  function render(next){state=next||state;const shown=visualState(state);for(const[name,element]of Object.entries(meters))if(element)element.style.width=`${clamp01(shown[name])*100}%`;root.PercussionDisplay?.render(shown.percussion||{});root.WebGLMusicVisualizer?.render(shown)}
  function renderLighting(next){if(!lightingButton||!lightingStatus)return;if(!next.available){lightingButton.disabled=true;lightingButton.textContent='MUSIC LIGHTING UNAVAILABLE';lightingStatus.textContent='No lighting controller is attached to this WebUI runtime.';return}lightingButton.disabled=false;lightingButton.textContent=next.enabled?'DISABLE MUSIC LIGHTING':'ENABLE MUSIC LIGHTING';lightingStatus.textContent=next.connected?(next.enabled?'Music-reactive lighting enabled.':'Lighting connected · manual control retained.'):(next.enabled?'Music lighting enabled, waiting for hardware connection.':'Lighting backend available · hardware disconnected.')}
  async function refreshLighting(){if(!lightingButton)return;try{const response=await fetch('/api/audio-analysis/lighting');if(!response.ok)throw Error(`HTTP ${response.status}`);renderLighting(await response.json())}catch(error){lightingButton.disabled=true;if(lightingStatus)lightingStatus.textContent=`Lighting status error: ${error.message}`}}
  async function refreshSongRecognition(){if(!songButton)return;try{const response=await fetch('/api/song-recognition/config'),config=await response.json();songButton.disabled=!config.configured;if(songStatus)songStatus.textContent=config.configured?`${config.provider||'Song recognition'} ready. Start an audio source, then identify.`:'No song recognition provider configured.'}catch(error){songButton.disabled=true;if(songStatus)songStatus.textContent=`Recognition status error: ${error.message}`}}
  async function stopMicrophone(){if(!capture.running)return;await capture.stop();button.textContent='START MICROPHONE'}
  async function pollLinux(){if(!linuxRunning)return;try{const response=await fetch('/api/audio-analysis/linux/state',{cache:'no-store'});if(!response.ok)throw Error(`HTTP ${response.status}`);const next=await response.json();linuxRunning=!!next.running;render(next);if(status)status.textContent=linuxRunning?'System audio active · PipeWire → shared MusicAnalyzer → WebGL':'System audio stopped.';if(linuxButton)linuxButton.textContent=linuxRunning?'STOP SYSTEM AUDIO':'START SYSTEM AUDIO'}catch(error){linuxRunning=false;if(status)status.textContent=`System audio error: ${error.message}`;if(linuxButton)linuxButton.textContent='START SYSTEM AUDIO'}finally{if(linuxRunning)linuxPoll=setTimeout(pollLinux,50)}}
  async function stopLinux(){if(linuxPoll){clearTimeout(linuxPoll);linuxPoll=null}if(!linuxRunning)return;await fetch('/api/audio-analysis/linux/stop',{method:'POST'});linuxRunning=false;if(linuxButton)linuxButton.textContent='START SYSTEM AUDIO'}
  button.onclick=async()=>{try{if(capture.running){await stopMicrophone();status.textContent='Microphone stopped.'}else{await stopLinux();await capture.start(render);button.textContent='STOP MICROPHONE';status.textContent='Microphone active · browser PCM → shared MusicAnalyzer → WebGL'}}catch(error){status.textContent=`Microphone error: ${error.message}`}};
  if(linuxButton)linuxButton.onclick=async()=>{try{if(linuxRunning){await stopLinux();status.textContent='System audio stopped.';return}await stopMicrophone();const response=await fetch('/api/audio-analysis/linux/start',{method:'POST'}),next=await response.json();if(!response.ok)throw Error(next.error||`HTTP ${response.status}`);linuxRunning=!!next.running;linuxButton.textContent=linuxRunning?'STOP SYSTEM AUDIO':'START SYSTEM AUDIO';render(next);status.textContent=linuxRunning?'System audio active · PipeWire → shared MusicAnalyzer → WebGL':'System audio did not start.';if(linuxRunning)pollLinux()}catch(error){linuxRunning=false;linuxButton.textContent='START SYSTEM AUDIO';status.textContent=`System audio error: ${error.message}`}};
  if(sensitivity){const syncSensitivity=()=>{if(sensitivityValue)sensitivityValue.textContent=`${visualGain().toFixed(0)}×`;render(state)};sensitivity.addEventListener('input',syncSensitivity);syncSensitivity()}
  if(lightingButton)lightingButton.onclick=async()=>{try{const current=await fetch('/api/audio-analysis/lighting').then(r=>r.json()),response=await fetch('/api/audio-analysis/lighting',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:!current.enabled})}),next=await response.json();if(!response.ok)throw Error(next.error||`HTTP ${response.status}`);renderLighting(next)}catch(error){if(lightingStatus)lightingStatus.textContent=`Lighting control error: ${error.message}`}};
  if(songButton)songButton.onclick=async()=>{songButton.disabled=true;try{if(songStatus)songStatus.textContent='Listening for 8 seconds…';const clip=await capture.recordClip(8000);if(songStatus)songStatus.textContent='Identifying…';const response=await fetch('/api/song-recognition/identify',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:clip}),result=await response.json();if(!response.ok)throw Error(result.error||`HTTP ${response.status}`);if(!result.matched){if(songStatus)songStatus.textContent='No song match found.'}else{const song=result.song;if(songTitle)songTitle.textContent=song.title||'Unknown title';if(songArtist)songArtist.textContent=(song.artists||[]).join(', ')||'Unknown artist';if(songAlbum)songAlbum.textContent=song.album||'';if(songStatus)songStatus.textContent=`Identified by ${result.provider||'song recognition'}.`}}catch(error){if(songStatus)songStatus.textContent=`Recognition error: ${error.message}`}finally{songButton.disabled=false}};
  root.WebGLMusicVisualizer?.install();root.PercussionDisplay?.install();render(state);refreshLighting();refreshSongRecognition();
})();
