(()=>{
  const root=window.OpenRoadCodeWeb=window.OpenRoadCodeWeb||{};
  const button=document.getElementById('music-mic-toggle'),status=document.getElementById('music-mic-status'),spectrum=document.getElementById('music-spectrum'),labels=document.getElementById('music-spectrum-labels'),debug=document.getElementById('music-debug');
  if(!button||!spectrum||!root.BrowserPcmCapture)return;

  function ensureStyles(){if(document.getElementById('music-visualizer-css'))return;const link=document.createElement('link');link.id='music-visualizer-css';link.rel='stylesheet';link.href='/web-assets/audio-analysis/music_visualizer.css?v=4';document.head.appendChild(link)}
  function ensureDrumKit(){if(document.getElementById('music-drum-kit'))return;const anchor=document.getElementById('music-beat');if(!anchor)return;const card=document.createElement('div');card.id='music-drum-kit';card.className='card mv-drum-card';card.innerHTML=`<div class="mv-section-title">DRUM KIT <span class="mv-subtle">shared percussion classifier</span></div><div class="mv-kit"><div id="drum-cymbal-left" class="mv-cymbal mv-cymbal-left"></div><span class="mv-kit-name mv-name-hihat">HI-HAT</span><div id="drum-cymbal-right" class="mv-cymbal mv-cymbal-right"></div><span class="mv-kit-name mv-name-crash">CRASH</span><span class="mv-drum-label mv-label-tom-high">HIGH TOM</span><div id="drum-tom-high" class="mv-drum mv-tom mv-tom-high"></div><span class="mv-drum-label mv-label-tom-mid">MID TOM</span><div id="drum-tom-mid" class="mv-drum mv-tom mv-tom-mid"></div><span class="mv-drum-label mv-label-tom-low">LOW TOM</span><div id="drum-tom-low" class="mv-drum mv-tom mv-tom-low"></div><span class="mv-drum-label mv-label-snare">SNARE</span><div id="drum-snare" class="mv-drum mv-snare"></div><div id="drum-kick-left" class="mv-drum mv-kick mv-kick-left"><span class="mv-drum-label">LEFT KICK</span></div><div id="drum-kick-right" class="mv-drum mv-kick mv-kick-right"><span class="mv-drum-label">RIGHT KICK</span></div></div>`;anchor.after(card)}
  function ensureActivityMeters(){if(document.getElementById('mv-activity'))return;const kit=document.getElementById('music-drum-kit');if(!kit)return;const card=document.createElement('div');card.id='mv-activity';card.className='card mv-activity-card';const meter=(name,id,cls)=>`<div class="mv-meter ${cls}"><div class="mv-meter-name">${name}</div><div id="${id}" class="mv-segments">${'<i class="mv-segment"></i>'.repeat(12)}</div></div>`;card.innerHTML=`<div class="mv-section-title">PERCUSSION ACTIVITY</div><div class="mv-meter-grid mv-meter-grid-six">${meter('KICK','mv-seg-kick','mv-kick-color')}${meter('SNARE','mv-seg-snare','mv-snare-color')}${meter('HIGH TOM','mv-seg-tomHigh','mv-tom-high-color')}${meter('MID TOM','mv-seg-tomMid','mv-tom-mid-color')}${meter('LOW TOM','mv-seg-tomLow','mv-tom-low-color')}${meter('CYMBAL','mv-seg-cymbal','mv-cymbal-color')}</div>`;kit.after(card)}
  function installUi(){ensureStyles();ensureDrumKit();ensureActivityMeters();root.SpectrumDisplay?.install();root.KickMode?.install();root.WebGLMusicVisualizer?.install();return !!document.getElementById('mv-webgl-mode')}
  installUi();let installAttempts=0;const installTimer=setInterval(()=>{if(installUi()||++installAttempts>40)clearInterval(installTimer)},50);

  const capture=new root.BrowserPcmCapture();
  const bars=Array.from({length:24},()=>{const x=document.createElement('div');x.style.cssText='flex:1;min-width:0;height:2%;background:linear-gradient(to top,#20c85a 0%,#34d058 34%,#dbe63b 48%,#ffd21c 62%,#ff8a18 78%,#ef3b24 100%);border-radius:4px 4px 0 0;transition:height .025s linear';spectrum.appendChild(x);return x});
  ['31','41','54','70','92','120','157','205','268','350','457','597','780','1k','1.3k','1.7k','2.2k','2.9k','3.8k','5k','6.5k','8.5k','11k','16k'].forEach((label,i)=>{const x=document.createElement('div');x.textContent=(i%2===0||i===23)?label:'';labels.appendChild(x)});

  const pulse={snare:0,tomHigh:0,tomMid:0,tomLow:0,cymbal:0};
  const setPunch=(id,value,color,base='',amount)=>{const el=document.getElementById(id);if(!el)return;const growth=amount??(id.includes('snare')?.22:id.includes('tom-mid')?.26:id.includes('tom-')?.24:id.includes('kick')?.34:.20);el.style.transform=`${base} scale(${1+value*growth})`;el.style.filter=`brightness(${1+value*.28}) saturate(${1+value*.34})`;el.style.boxShadow=`inset 0 0 ${5+value*9}px ${color},0 0 ${8+value*25}px ${color}`};
  function renderMeter(id,value,color){const seg=document.getElementById(id);if(!seg)return;const on=Math.round(Math.max(0,Math.min(1,value))*12);[...seg.children].forEach((x,i)=>{x.style.background=i<on?color:'#18222e';x.style.opacity=i<on?1:.55})}
  function renderDrums(p){for(const key of Object.keys(pulse))pulse[key]=Math.max(p[key]||0,pulse[key]*.72);root.KickMode?.render(p.kick||0,setPunch);setPunch('drum-snare',pulse.snare,'rgba(255,198,46,.68)','translateX(-50%)');setPunch('drum-tom-high',pulse.tomHigh,'rgba(168,76,255,.68)');setPunch('drum-tom-mid',pulse.tomMid,'rgba(56,214,180,.68)');setPunch('drum-tom-low',pulse.tomLow,'rgba(40,182,255,.68)');const c=pulse.cymbal;for(const[id,dir]of[['drum-cymbal-left',-1],['drum-cymbal-right',1]]){const el=document.getElementById(id);if(el){el.style.transform=`scaleX(${1+c*.17}) scaleY(${1+c*.09}) rotate(${dir*c*9}deg)`;el.style.filter=`brightness(${1+c*.5}) saturate(${1+c*.32})`}}renderMeter('mv-seg-kick',p.kick||0,'#ff4939');renderMeter('mv-seg-snare',p.snare||0,'#ffc62e');renderMeter('mv-seg-tomHigh',p.tomHigh||0,'#a84cff');renderMeter('mv-seg-tomMid',p.tomMid||0,'#38d6b4');renderMeter('mv-seg-tomLow',p.tomLow||0,'#28b6ff');renderMeter('mv-seg-cymbal',p.cymbal||0,'#ffd235')}
  function normalize(payload){const a=payload?.audio||payload||{},p=payload?.percussion||{};return{level:a.level||0,peak:a.peak||0,bass:a.bass||0,mid:a.mid||0,treble:a.treble||0,spectrum:a.spectrum||[],percussion:{kick:p.kick||0,snare:p.snare||0,tomLow:p.tom_low??p.tomLow??0,tomMid:p.tom_mid??p.tomMid??0,tomHigh:p.tom_high??p.tomHigh??0,cymbal:p.cymbal||0},calibrated:!!(payload?.ui?.calibrated??payload?.calibrated),sensitivity:payload?.ui?.sensitivity??payload?.sensitivity??1,status:payload?.ui?.status||'active'}}
  function render(payload){const s=normalize(payload);root.WebGLMusicVisualizer?.render(s);document.getElementById('music-level').value=s.level;document.getElementById('music-bass').value=s.bass;document.getElementById('music-mid').value=s.mid;document.getElementById('music-treble').value=s.treble;document.getElementById('activity-kick').value=s.percussion.kick;document.getElementById('activity-bass').value=s.bass;document.getElementById('activity-snare').value=s.percussion.snare;document.getElementById('activity-cymbal').value=s.percussion.cymbal;root.SpectrumDisplay?.render(payload,bars);renderDrums(s.percussion);if(debug)debug.textContent=`Shared Python MusicAnalyzer · ${s.status} · sensitivity ${Math.round(s.sensitivity*100)}%${s.calibrated?' · zeroized':''}`}
  root.MusicVisualizerPage={render};
  button.onclick=async()=>{const enabled=button.dataset.enabled==='1';try{if(enabled){await capture.stop();button.dataset.enabled='0';button.textContent='START MICROPHONE';status.textContent='Microphone stopped.';root.SpectrumDisplay?.setCaptureActive(false)}else{root.SpectrumDisplay?.setSource('browser');await capture.start(render);button.dataset.enabled='1';button.textContent='STOP MICROPHONE';status.textContent='Microphone active · browser captures PCM; Python analyzes it.';root.SpectrumDisplay?.setCaptureActive(true)}}catch(error){status.textContent=`Microphone error: ${error.message}`}};
})();