(()=>{const root=window.OpenRoadCodeWeb=window.OpenRoadCodeWeb||{},names=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'];
const noteFromHz=f=>{if(!f||f<=0)return null;const midi=Math.round(69+12*Math.log2(f/440));return{midi,name:names[(midi%12+12)%12]+(Math.floor(midi/12)-1),hz:f,cents:1200*Math.log2(f/(440*Math.pow(2,(midi-69)/12)))}};
class HarmonicPitchTracker{constructor(){this.previous={bass:null,treble:null};this.hold={bass:0,treble:0}}
track(freqDb,sampleRate,fftSize){return{bass:this._band(freqDb,sampleRate,fftSize,41,330,'bass'),treble:this._band(freqDb,sampleRate,fftSize,165,1800,'treble')}}
_band(data,sr,n,min,max,key){const binHz=sr/n,lo=Math.max(2,Math.ceil(min/binHz)),hi=Math.min(data.length-2,Math.floor(max/binHz));let best=null,bestScore=0,noise=0,count=0;for(let i=lo;i<=hi;i++){const db=data[i];if(Number.isFinite(db)){noise+=Math.pow(10,db/20);count++}}noise=Math.max(1e-8,noise/Math.max(1,count));for(let i=lo;i<=hi;i++){const a=Math.pow(10,data[i]/20);if(a<noise*1.25)continue;let score=a;for(let h=2;h<=5;h++){const j=i*h;if(j>=data.length)break;score+=Math.pow(10,data[j]/20)*(1/(h*.72))}const half=Math.round(i/2);if(half>=lo)score-=Math.pow(10,data[half]/20)*.18;if(score>bestScore){bestScore=score;best=i}}if(best===null||bestScore<noise*1.7){this.hold[key]++;return this.hold[key]<7?this.previous[key]:null}let idx=best;if(best>1&&best<data.length-1){const y1=data[best-1],y2=data[best],y3=data[best+1],den=y1-2*y2+y3;if(Math.abs(den)>1e-6)idx=best+.5*(y1-y3)/den}let result=noteFromHz(idx*binHz);const prev=this.previous[key];if(prev&&result&&Math.abs(result.midi-prev.midi)>7&&bestScore<noise*3.5)result=prev;this.previous[key]=result;this.hold[key]=0;return result}}
function install(){if(document.getElementById('mv-pitch'))return;const css=document.createElement('link');css.rel='stylesheet';css.href='/web-assets/audio-analysis/pitch_visualizer.css?v=1';document.head.appendChild(css);const after=document.getElementById('mv-activity')||document.getElementById('music-drum-kit');if(!after)return;const lines='<i class="mv-staff-line"></i>'.repeat(5),c=document.createElement('div');c.id='mv-pitch';c.className='card mv-pitch-card';c.innerHTML=`<div class="mv-section-title">LIVE PITCH <span class="mv-subtle">harmonic estimate</span></div><div class="mv-pitch-readouts"><div class="mv-pitch-readout"><span>BASS</span><b id="mv-pitch-bass-name">—</b><span id="mv-pitch-bass-hz"></span></div><div class="mv-pitch-readout"><span>TREBLE</span><b id="mv-pitch-treble-name">—</b><span id="mv-pitch-treble-hz"></span></div></div><div class="mv-grand-staff"><div class="mv-staff mv-staff-treble">${lines}<span class="mv-clef mv-clef-treble">𝄞</span><i id="mv-note-treble" class="mv-note-head mv-note-treble"></i><span id="mv-label-treble" class="mv-pitch-note-label mv-pitch-note-label-treble"></span></div><div class="mv-staff mv-staff-bass">${lines}<span class="mv-clef mv-clef-bass">𝄢</span><i id="mv-note-bass" class="mv-note-head mv-note-bass"></i><span id="mv-label-bass" class="mv-pitch-note-label mv-pitch-note-label-bass"></span></div></div><p class="mv-pitch-help">Polyphonic music can fool this. The display follows the strongest harmonically plausible bass and melodic pitches.</p>`;after.after(c)}
function staffY(midi,key){const base=key==='bass'?43:64;return 80-(midi-base)*5}
function renderOne(key,n){const name=document.getElementById(`mv-pitch-${key}-name`),hz=document.getElementById(`mv-pitch-${key}-hz`),head=document.getElementById(`mv-note-${key}`),label=document.getElementById(`mv-label-${key}`);if(!name)return;if(!n){name.textContent='—';hz.textContent='';if(head)head.style.opacity=.12;if(label)label.textContent='';return}name.textContent=n.name;hz.textContent=`${n.hz.toFixed(1)} Hz`;const y=Math.max(-12,Math.min(92,staffY(n.midi,key)));if(head){head.style.top=`${y}px`;head.style.opacity=.95}if(label){label.style.top=`${y-18}px`;label.textContent=n.name}}
root.PitchVisualizer={install,render:p=>{renderOne('bass',p?.bass);renderOne('treble',p?.treble)}};root.HarmonicPitchTracker=HarmonicPitchTracker;setTimeout(install,0)})();
