(()=>{
 const root=window.OpenRoadCodeWeb=window.OpenRoadCodeWeb||{};let activeSource='browser',captureActive=false;
 function install(){const mic=document.getElementById('music-mic-toggle'),spectrum=document.getElementById('music-spectrum');if(!mic||!spectrum)return false;if(!document.getElementById('spectrum-zeroize-controls')){const top=document.createElement('div');top.id='spectrum-zeroize-controls';top.className='mv-zeroize-controls';top.innerHTML=`<button id="spectrum-zeroize" type="button" class="wide" disabled>ZEROIZE ROOM NOISE</button><div id="spectrum-analysis-state" class="mv-analysis-state">Start the microphone before zeroizing.</div>`;mic.insertAdjacentElement('afterend',top);document.getElementById('spectrum-zeroize').onclick=startZeroize}if(!document.getElementById('spectrum-display-controls')){const card=spectrum.closest('.card'),controls=document.createElement('div');controls.id='spectrum-display-controls';controls.className='mv-spectrum-controls';controls.innerHTML=`<label>SPECTRUM ANALYSIS<select id="spectrum-analysis-mode" class="search"><option value="native">Native</option><option value="normalized">Normalized</option><option value="hybrid" selected>Hybrid</option></select></label><label>SENSITIVITY <span id="spectrum-sensitivity-value">100%</span><input id="spectrum-sensitivity" type="range" min="25" max="200" value="100" step="5"></label>`;card.appendChild(controls);document.getElementById('spectrum-analysis-mode').onchange=e=>setSpectrumMode(e.target.value);document.getElementById('spectrum-sensitivity').oninput=e=>{document.getElementById('spectrum-sensitivity-value').textContent=e.target.value+'%';setSensitivity(Number(e.target.value)/100)}}return true}
 function endpoint(action){return `/api/audio-analysis/${activeSource}/${action}`}
 async function fetchState(){const r=await fetch(endpoint('state'),{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error||`HTTP ${r.status}`);return j}
 function syncState(p){const ui=p?.ui||{},state=ui.status||(captureActive?'active':'stopped'),cal=ui.calibrated??p?.calibrated??false,sens=ui.sensitivity??p?.sensitivity,b=document.getElementById('spectrum-zeroize'),label=document.getElementById('spectrum-analysis-state'),mode=document.getElementById('spectrum-analysis-mode');if(mode&&p?.spectrum_mode&&document.activeElement!==mode)mode.value=p.spectrum_mode;if(b){b.disabled=!captureActive||state==='zeroizing';b.style.display=captureActive?'block':'none';b.textContent=state==='zeroizing'?'ZEROIZING… KEEP MUSIC OFF':(cal?'RE-ZEROIZE ROOM NOISE':'ZEROIZE ROOM NOISE')}if(Number.isFinite(sens)){const slider=document.getElementById('spectrum-sensitivity'),v=document.getElementById('spectrum-sensitivity-value'),pct=Math.round(sens*100);if(slider&&document.activeElement!==slider)slider.value=String(pct);if(v)v.textContent=pct+'%'}if(label){label.style.display=captureActive?'block':'none';label.textContent=state==='zeroizing'?'ZEROIZING · sampling ambient room/vehicle noise…':state==='active'?(cal?'ACTIVE · ambient floor applied to spectrum + percussion.':'ACTIVE · not zeroized yet.'):state==='error'?'ANALYSIS ERROR · '+(ui.error||p?.error||'unknown error'):String(state).toUpperCase()}}
 async function startZeroize(){if(!captureActive)return;try{let r=await fetch(endpoint('zeroize'),{method:'POST'}),j=await r.json();if(!r.ok)throw Error(j.error||`HTTP ${r.status}`);syncState(j);const deadline=Date.now()+5000;while(Date.now()<deadline){await new Promise(x=>setTimeout(x,120));j=await fetchState();syncState(j);if(j?.ui?.status==='active'&&(j.ui.calibrated??j.calibrated))return}throw Error('Calibration did not complete; verify PCM frames are arriving')}catch(e){const b=document.getElementById('spectrum-zeroize'),l=document.getElementById('spectrum-analysis-state');if(b){b.disabled=false;b.textContent='ZEROIZE FAILED'}if(l)l.textContent='ZEROIZE FAILED · '+e.message}}
 async function setSensitivity(value){try{const r=await fetch(endpoint('sensitivity'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({value})}),j=await r.json();if(!r.ok)throw Error(j.error||`HTTP ${r.status}`);syncState(j)}catch(e){console.warn(e)}}
 async function setSpectrumMode(value){try{const r=await fetch(endpoint('spectrum-mode'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({value})}),j=await r.json();if(!r.ok)throw Error(j.error||`HTTP ${r.status}`);syncState(j)}catch(e){console.warn('Spectrum mode update failed',e)}}
 function setCaptureActive(v){captureActive=!!v;if(captureActive)fetchState().then(syncState).catch(()=>{});else syncState({ui:{status:'stopped',calibrated:false}})}function setSource(s){activeSource=s==='linux'?'linux':'browser';fetchState().then(syncState).catch(()=>{})}function render(state,bars){const values=state?.audio?.spectrum||state?.spectrum||[];values.forEach((v,i)=>{if(bars[i])bars[i].style.height=`${Math.max(1,Math.max(0,Math.min(1,v))*100)}%`});syncState(state)}root.SpectrumDisplay={install,render,startZeroize,setCaptureActive,setSource,syncState,setSpectrumMode};
})();