(()=>{
  const root=window.OpenRoadCodeWeb=window.OpenRoadCodeWeb||{};
  let activeSource='browser',captureActive=false;
  function install(){
    const spectrum=document.getElementById('music-spectrum');if(!spectrum||document.getElementById('spectrum-display-controls'))return false;
    const controls=document.createElement('div');controls.id='spectrum-display-controls';controls.style.cssText='display:grid;gap:12px;width:100%;min-width:0;box-sizing:border-box;margin:12px 0 4px';controls.innerHTML=`<label style="font-size:12px;color:#c5d0db">SENSITIVITY <span id="spectrum-sensitivity-value">100%</span><input id="spectrum-sensitivity" type="range" min="25" max="200" value="100" step="5" style="width:100%;margin-top:8px"></label><button id="spectrum-zeroize" type="button" class="wide" style="min-height:48px" disabled>ZEROIZE ROOM NOISE</button><div id="spectrum-analysis-state" style="font-size:11px;color:#82909d">Analysis source stopped.</div>`;spectrum.parentNode.insertBefore(controls,spectrum);
    document.getElementById('spectrum-zeroize').onclick=startZeroize;document.getElementById('spectrum-sensitivity').oninput=e=>{document.getElementById('spectrum-sensitivity-value').textContent=e.target.value+'%';setSensitivity(Number(e.target.value)/100)};return true;
  }
  function endpoint(action){return `/api/audio-analysis/${activeSource}/${action}`}
  async function fetchState(){const r=await fetch(endpoint('state'),{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error||`HTTP ${r.status}`);return j}
  function syncState(payload){const ui=payload?.ui||{},state=ui.status||(captureActive?'active':'stopped'),calibrated=ui.calibrated??payload?.calibrated??false,sensitivity=ui.sensitivity??payload?.sensitivity,b=document.getElementById('spectrum-zeroize'),label=document.getElementById('spectrum-analysis-state');if(b){b.disabled=!captureActive||state==='zeroizing';b.textContent=state==='zeroizing'?'ZEROIZING… KEEP MUSIC OFF':(calibrated?'RE-ZEROIZE ROOM NOISE':'ZEROIZE ROOM NOISE')}if(Number.isFinite(sensitivity)){const slider=document.getElementById('spectrum-sensitivity'),value=document.getElementById('spectrum-sensitivity-value'),pct=Math.round(sensitivity*100);if(slider&&document.activeElement!==slider)slider.value=String(pct);if(value)value.textContent=pct+'%'}if(label){if(state==='zeroizing')label.textContent='ZEROIZING · keep music off while ambient noise is sampled.';else if(state==='error')label.textContent='ANALYSIS ERROR · '+(ui.error||payload?.error||'unknown error');else if(state==='active')label.textContent=calibrated?'ACTIVE · ambient noise calibration applied.':'ACTIVE · not zeroized yet.';else label.textContent=String(state).toUpperCase()}}
  async function startZeroize(){const b=document.getElementById('spectrum-zeroize');try{const r=await fetch(endpoint('zeroize'),{method:'POST'}),j=await r.json();if(!r.ok)throw Error(j.error||`HTTP ${r.status}`);syncState(j);const deadline=Date.now()+4000;while(Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,150));const state=await fetchState();syncState(state);if(state?.ui?.status==='active'&&(state.ui.calibrated??state.calibrated))return}throw Error('Calibration did not complete while audio frames were arriving')}catch(e){if(b){b.disabled=false;b.textContent='ZEROIZE FAILED'}const label=document.getElementById('spectrum-analysis-state');if(label)label.textContent='ZEROIZE FAILED · '+e.message;console.warn(e)}}
  async function setSensitivity(value){try{const r=await fetch(endpoint('sensitivity'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({value})}),j=await r.json();if(!r.ok)throw Error(j.error||`HTTP ${r.status}`);syncState(j)}catch(e){console.warn('Sensitivity update failed',e)}}
  function setCaptureActive(active){captureActive=!!active;if(captureActive)fetchState().then(syncState).catch(()=>{});else syncState({ui:{status:'stopped',calibrated:false}})}
  function setSource(source){activeSource=source==='linux'?'linux':'browser';if(captureActive)fetchState().then(syncState).catch(()=>{})}
  function render(state,bars){const spectrum=state?.audio?.spectrum||state?.spectrum||[];spectrum.forEach((v,i)=>{if(bars[i])bars[i].style.height=`${Math.max(2,Math.max(0,Math.min(1,v))*100)}%`});syncState(state)}
  root.SpectrumDisplay={install,render,startZeroize,setCaptureActive,setSource,syncState};
})();