# SPDX-FileCopyrightText: 2026 Mark G. Russell
# SPDX-License-Identifier: MIT

"""Reference layout metrics for the integrated 1280x720 orcUi shell."""

TARGET_WIDTH = 1280
TARGET_HEIGHT = 720
TARGET_GEOMETRY = f"{TARGET_WIDTH}x{TARGET_HEIGHT}"

TOP_BAR_HEIGHT = 60
BOTTOM_BAR_HEIGHT = 66
FOOTER_HEIGHT = 22
SIDE_NAV_WIDTH = 140
CONTEXT_RAIL_WIDTH = 340

SHELL_PAD_X = 10
SHELL_PAD_Y = 8
CONTROL_PAD_X = 6

FONT_TINY = 8
FONT_SMALL = 9
FONT_CONTROL = 10
FONT_BODY = 11
FONT_STATUS = 12
FONT_CLOCK = 19
FONT_BRAND = 23
FONT_POWER = 18
